# Generated by Django 5.0.6 on 2024-06-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seller_alter_realestate_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_day',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_month',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_year',
            field=models.FloatField(default=None, null=True),
        ),
    ]
