# Generated by Django 5.0.6 on 2024-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_realestatedetails_price_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_day',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_month',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='price_per_year',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
